name: Build and publish forkdiff github-pages
permissions:
  contents: write
on:
  push:
    branches:
      - portal
jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    depends-on: copy-and-clone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shisui
        uses: actions/checkout@v3
        with:
          path: /github/workspace/shisui
          fetch-depth: 1
      - name: Checkout go-ethereum
        uses: actions/checkout@v3
        with:
          repository: ethereum/go-ethereum
          path: /github/workspace/go-ethereum
          ref: master
          fetch-depth: 1
      - name: Build forkdiff
        uses: "docker://protolambda/forkdiff:latest"
        with:
          args: -repo=/github/workspace  -fork=/github/workspace/fork.yaml -out=/github/workspace/index.html

      - name: Build pages
        run: |
          mkdir -p tmp/pages
          mv index.html tmp/pages/index.html
          touch tmp/pages/.nojekyll
          if [ "$GITHUB_REPOSITORY" == "optimism-java/shisui" ]; then
              echo "shisui.github.io" > tmp/pages/CNAME
          fi;

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: tmp/pages
          clean: true
